const cryptoWords = [
    "blockchain",
    "Blockchain",
    "cryptocurrency",
    "Cryptocurrency",
    "bitcoin",
    "Bitcoin",
    "ethereum",
    "Ethereum",
    "smart contract",
    "Smart Contract",
    "decentralized",
    "Decentralized",
    "ledger",
    "Ledger",
    "mining",
    "Mining",
    "hash",
    "Hash",
    "Doge",
    "doge",
    "wallet",
    "Wallet",
    "token",
    "Token",
    "ico",
    "ICO",
    "defi",
    "DeFi",
    "staking",
    "Staking",
    "consensus",
    "Consensus",
    "protocol",
    "Protocol",
    "peer-to-peer",
    "Peer-to-Peer",
    "gas",
    "Gas",
    "nft",
    "NFT",
    "proof of work",
    "Proof of Work",
    "proof of stake",
    "Proof of Stake",
    "public key",
    "Public Key",
    "private key",
    "Private Key",
    "address",
    "Address",
    "transaction",
    "Transaction",
    "block",
    "Block",
    "dapp",
    "dApp",
    "exchange",
    "Exchange",
    "fomo",
    "FOMO",
    "fud",
    "FUD",
    "whale",
    "Whale",
    "airdrops",
    "Airdrops",
    "liquidity",
    "Liquidity",
    "satoshi",
    "Satoshi",
];

const alephiumWords = [
    "alephium",
    "Alephium",
];

const epflWords = [
    "epfl",
    "EPFL",
];

// Combine all words into one array
export const allWords = [...cryptoWords, ...alephiumWords, ...epflWords];

